export default [
  'Arrays',
  'Hashing',
  'Stack',
  'Two Pointers',
  'Binary Search',
  'Sliding Window',
  'Linked List',
  'Trees',
  'Tries',
  'Backtracking',
  'Heap / Priority Queue',
  'Graphs',
  'Advanced Graphs',
  'Intervals',
  'Greedy',
  '1-D Dynamic Programming',
  '2-D Dynamic Programming',
  'Bit Manipulation',
  'Math & Geometry',
];
